# Temporal Analysis of IDEA Diagnoses

Data Downloaded from: https://data.ed.gov/dataset/idea-section-618-lea-part-b-child-count/resources?resource=0e0a1a55-57f5-4e50-b66e-1a68949e38f3

(2020-2022)

In [15]:
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

from IDEA_loader import load_IDEA

In [16]:
# Just looking at school age children, so removing "Early Childhood"

IDEA_COLS_TO_DROP = [
    'Combined Early Childhood and School Age Total',
    'Early Childhood All Disabilities',
    'Early Childhood Autism',
    'Early Childhood Deaf-blindness',
    'Early Childhood Developmental Delay',
    'Early Childhood Emotional Disturbance',
    'Early Childhood Hearing Impairment',
    'Early Childhood Intellectual Disability',
    'Early Childhood Multiple Disabilities',
    'Early Childhood Orthopedic Impairment',
    'Early Childhood Other Health Impairment',
    'Early Childhood Specific Learning Disability',
    'Early Childhood Speech or Language Impairment',
    'Early Childhood Traumatic Brain Injury',
    'Early Childhood Visual Impairment',
    'Early Childhood Missing',
    
    # gives no information (all 0s)
    'School Age Missing'
]

IDEA_COL_MAPPING = {
    'School Age All Disabilities' : 'All Disabilites',
    'School Age Autism' : 'Autism',
    'School Age Deaf-blindness' : 'Deaf-blindness',
    'School Age Developmental Delay': 'Developmental Delay',
    'School Age Emotional Disturbance': 'Emotional Disturbance',
    'School Age Hearing Impairment' : 'Hearing Impariment',
    'School Age Intellectual Disability' : 'Intellectual Disability',
    'School Age Multiple Disabilities' : 'Multiple Disabilities',
    'School Age Orthopedic Impairment' : 'Orthopedic Impairment',
    'School Age Other Health Impairment' : 'Other Health Impairment',
    'School Age Specific Learning Disability': 'Specific Learning Disability',
    'School Age Speech or Language Impairment' : 'Speech or Language Impairment',
    'School Age Traumatic Brain Injury': 'Traumatic Brain Injury',
    'School Age Visual Impairment': 'Visual Impairment',

    'NCES LEA ID': 'LEAID'
}

In [ ]:
# combine multiple IDEA reports (2021-2023) into one dataframe.

# store the file names along with the amount of rows to skip at the top of each file.
files = {
    'bchildcountandedenvironmentlea2020-21.csv': 0,
    'bchildcountandedenvironmentlea2021-22.csv':4,
    'bchildcountdisabilitycategorylea2022-23.csv':4
}

dfs = [] 

for file_name in files.keys():
    rows_to_skip = files[file_name]

    df = load_IDEA(file_name,
                skip_rows=rows_to_skip,
                drop_columns=IDEA_COLS_TO_DROP,
                column_mappings=IDEA_COL_MAPPING
                )
    
    dfs.append(df)

idea_df = pd.concat(dfs, ignore_index=True)

c:\Projects\SEEN\paper_2\IDEA_loader.py:21: DtypeWarning: Columns (4) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(file_path, skiprows=skip_rows)

In [33]:
idea_df.head()

,School Year,State FIPS Code,State Name,LEA Name,State LEA ID,LEAID,All Disabilites,Autism,Deaf-blindness,Developmental Delay,Emotional Disturbance,Hearing Impariment,Intellectual Disability,Multiple Disabilities,Orthopedic Impairment,Other Health Impairment,Specific Learning Disability,Speech or Language Impairment,Traumatic Brain Injury,Visual Impairment
0,2020-2021,1,ALABAMA,Acceleration Day and Evening Academy,800,100197,50.0,5.0,0.0,0.0,0.0,NaN,NaN,0.0,0.0,17.0,23.0,0.0,0.0,NaN
1,2020-2021,1,ALABAMA,Al Inst Deaf And Blind,600,100009,332.0,0.0,3.0,0.0,0.0,166.0,NaN,59.0,0.0,0.0,0.0,NaN,0.0,101.0
2,2020-2021,1,ALABAMA,Alabama Clinical Schools,709,100183,39.0,NaN,0.0,0.0,5.0,0.0,3.0,NaN,0.0,12.0,14.0,NaN,0.0,0.0
3,2020-2021,1,ALABAMA,Alabama Youth Services,210,100002,17.0,0.0,0.0,0.0,NaN,0.0,NaN,0.0,0.0,4.0,8.0,NaN,0.0,0.0
4,2020-2021,1,ALABAMA,Alabaster City,103,100190,655.0,102.0,0.0,45.0,55.0,7.0,37.0,9.0,NaN,107.0,178.0,105.0,NaN,7.0

In [45]:
# pivot the table to combine rows for LEAs
index_cols = ['LEAID', 'LEA Name', 'State Name']
values_cols = ['All Disabilites', 'Autism', 'Deaf-blindness',
            'Developmental Delay', 'Emotional Disturbance', 'Hearing Impariment',
            'Intellectual Disability', 'Multiple Disabilities',
            'Orthopedic Impairment', 'Other Health Impairment',
            'Specific Learning Disability', 'Speech or Language Impairment',
            'Traumatic Brain Injury', 'Visual Impairment']

df_pivot = idea_df.pivot_table(
    index=index_cols,
    columns='School Year',
    values=values_cols
).reset_index()

# some magic to rename columns reasonably.
df_pivot.columns = index_cols + [f'{col[0]} {col[1]}' for col in df_pivot.columns[len(index_cols):]]

In [46]:
df_pivot

,LEAID,LEA Name,State Name,All Disabilites 2020-2021,All Disabilites 2021-2022,All Disabilites 2022-2023,Autism 2020-2021,Autism 2021-2022,Autism 2022-2023,Deaf-blindness 2020-2021,...,Specific Learning Disability 2022-2023,Speech or Language Impairment 2020-2021,Speech or Language Impairment 2021-2022,Speech or Language Impairment 2022-2023,Traumatic Brain Injury 2020-2021,Traumatic Brain Injury 2021-2022,Traumatic Brain Injury 2022-2023,Visual Impairment 2020-2021,Visual Impairment 2021-2022,Visual Impairment 2022-2023
0,100002,Alabama Youth Services,ALABAMA,17.0,21.0,24.0,0.0,0.0,0.0,0.0,...,9.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,100005,Albertville City,ALABAMA,452.0,465.0,491.0,32.0,39.0,38.0,0.0,...,168.0,156.0,131.0,160.0,0.0,NaN,NaN,0.0,NaN,NaN
2,100006,Marshall County,ALABAMA,811.0,776.0,724.0,67.0,66.0,82.0,0.0,...,350.0,137.0,130.0,112.0,NaN,NaN,3.0,6.0,5.0,6.0
3,100007,Hoover City,ALABAMA,1241.0,1263.0,1319.0,223.0,250.0,284.0,0.0,...,335.0,207.0,212.0,217.0,4.0,3.0,NaN,8.0,5.0,8.0
4,100008,Madison City,ALABAMA,1287.0,1301.0,1317.0,197.0,216.0,253.0,0.0,...,376.0,330.0,309.0,273.0,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
17679,5900197,Noli School,BUREAU OF INDIAN EDUCATION,13.0,18.0,9.0,0.0,4.0,0.0,0.0,...,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17680,5900200,Jones Academy,BUREAU OF INDIAN EDUCATION,6.0,8.0,10.0,0.0,NaN,0.0,0.0,...,5.0,3.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0
17681,7200030,PUERTO RICO DEPARTMENT OF EDUCATION,PUERTO RICO,89752.0,82666.0,84409.0,5809.0,6449.0,7763.0,13.0,...,35092.0,16213.0,14261.0,11372.0,23.0,25.0,24.0,270.0,226.0,221.0
17682,7800002,Saint Croix School District,U.S. VIRGIN ISLANDS,531.0,500.0,472.0,61.0,58.0,57.0,0.0,...,251.0,14.0,21.0,20.0,NaN,NaN,NaN,0.0,0.0,0.0
17683,7800030,Saint Thomas - Saint John School District,U.S. VIRGIN ISLANDS,459.0,446.0,370.0,44.0,48.0,41.0,0.0,...,156.0,68.0,70.0,61.0,NaN,NaN,NaN,5.0,5.0,5.0